import type { Metadata } from "next";
import { DM_Mono, Bitcount, Bitcount_Single } from "next/font/google";
import "./globals.css";

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-dm-mono",
  display: "swap",
});

const bitcount = Bitcount({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-bitcount",
  display: "swap",
});

const bitcountSingle = Bitcount_Single({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bitcount-single",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmMono.variable} ${bitcount.variable} ${bitcountSingle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
